language: emacs-lisp

env:
  matrix:
    - EMACS=emacs AKA=emacs23
    - EMACS=emacs24
    - EMACS=emacs-snapshot

install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get install -qq emacs23 emacs23-el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi

script:
  $EMACS --version && make test EMACS=${EMACS}