language: emacs-lisp

env:
  matrix:
    - EMACS=emacs AKA=emacs23
    - EMACS=emacs24
    - EMACS=emacs-snapshot

install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

script:
  $EMACS --version && make test EMACS=${EMACS}